# Generated by Django 3.2.13 on 2022-05-18 01:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gd',
            name='gd01',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='gd',
            name='gd02',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
